### ISSUE TITLE
[feature] springboot 도커 환경 설정

### ISSUE THREAD

**Issue by LeeJE20** [Wingle-SMWU/Wingle-Backend#1]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [feature] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- dockerfile 추가: 스프링부트 프로젝트 실행

## 📋 TODO
- [ ] dockerfile 추가
