### ISSUE TITLE
[refactor] 로깅 수정

### ISSUE THREAD

**Issue by yujin113** [Wingle-SMWU/Wingle-Backend#100]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 어떤 유저가 접근했는지에 대한 내용 포함

## 📋 TODO
- [x] 로깅 수정
