### ISSUE TITLE
[fix] 게시물 목록 보기 요청 경로 수정

### ISSUE THREAD

**Issue by LeeJE20** [Wingle-SMWU/Wingle-Backend#104]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- articles 뒤에 / 삭제해야함

## 📋 TODO
- [ ] articles 뒤에 / 삭제해야함
