### ISSUE TITLE
[fix] 댓글 작성 req 수정

### ISSUE THREAD

**Issue by Lightieey** [Wingle-SMWU/Wingle-Backend#105]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 설명을 작성해주세요

## 📋 TODO
- [ ] @ModelAttribute -> @RequestBody로 수정
- [ ] CommentRequestDto 수정
