### ISSUE TITLE
[feature] 관리자 페이지네이션 사이즈 조정

### ISSUE THREAD

**Issue by LeeJE20** [Wingle-SMWU/Wingle-Backend#108]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 15개->10개로 변경

## 📋 TODO
- [ ] 15개->10개로 변경
