### ISSUE TITLE
[fix] 게시글 삭제 시 댓글 삭제 추가

### ISSUE THREAD

**Issue by Lightieey** [Wingle-SMWU/Wingle-Backend#114]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [ ] 이슈 제목 작성 [FEATURE] 개발할 기능
- [ ] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 게시글 삭제 시 해당 게시글에 달린 댓글까지 모두 삭제하도록 수정

## 📋 TODO
- [ ] Service단에서 댓글까지 모두 soft delete 구현

**Comment by Lightieey** [comment]
프론트에서 처리하기로 함.
