### ISSUE TITLE
[bug] 메시지 없는 쪽지방 목록 보기 

### ISSUE THREAD

**Issue by LeeJE20** [Wingle-SMWU/Wingle-Backend#119]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 쪽지방만 존재하고 대화가 존재하지 않으면 목록 보기 불가

## 📋 TODO
- [ ] 쪽지방만 있어도 목록 볼 수 있게 하기
