### ISSUE TITLE
[feature] Member 엔티티 생성

### ISSUE THREAD

**Issue by yujin113** [Wingle-SMWU/Wingle-Backend#12]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- Member과 다른 엔티티랑 관계를 가지고 있는 부분이 많아서, 우선 Member 엔티티만 먼저 생성해서 올리겠습니다

## 📋 TODO
- [ ] Member 엔티티 생성
