### ISSUE TITLE
[bug] 쪽지 목록 보기 쪽지 없는 경우

### ISSUE THREAD

**Issue by LeeJE20** [Wingle-SMWU/Wingle-Backend#121]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 쪽지방만 있고 쪽지가 없는 경우 쪽지 목록 보기 하면 에러 발생

## 🎯 Goal
- 빈 배열 보내줘야 함

## 📋 TODO
- [ ] 쪽지가 없는 경우 에러 처리
