### ISSUE TITLE
[bug] 댓글 삭제 안되는 오류

### ISSUE THREAD

**Issue by Lightieey** [Wingle-SMWU/Wingle-Backend#126]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [ ] 이슈 제목 작성
- [ ] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 버그를 재현하려면 어떻게 해야 하는지
댓글을 새로 추가하고 삭제 요청 보내기
- 내가 한 행동 (구체적)
예전 댓글은 삭제되는데, 최근에 새로 단 댓글은 삭제가 안됨
- 이용 환경 (os, 브라우저 등등)

## 🎯 Goal
- 정상 동작이면 어떻게 되어야 하는지
정상적으로 삭제되어야 함

## 📋 TODO
- [ ] 할 일
