### ISSUE TITLE
[add] 게시글 res 유저이미지 추가

### ISSUE THREAD

**Issue by Lightieey** [Wingle-SMWU/Wingle-Backend#129]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [ ] 이슈 제목 작성 [FEATURE] 개발할 기능
- [ ] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 게시글(article) 관련 api response body에 userImage 추가

## 📋 TODO
- [ ]
