### ISSUE TITLE
[bug] profile 상세조회 image 오류

### ISSUE THREAD

**Issue by Lightieey** [Wingle-SMWU/Wingle-Backend#131]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [ ] 이슈 제목 작성
- [ ] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 버그를 재현하려면 어떻게 해야 하는지
프로필 저장을 안했는데, 프로필 상세조회에서 이미지가 나옴
- 내가 한 행동 (구체적)
- 이용 환경 (os, 브라우저 등등)

## 🎯 Goal
- 정상 동작이면 어떻게 되어야 하는지
프로필 저장을 안했으면 이미지가 null로 리턴되어야 함

## 📋 TODO
- [ ] 할 일
