### ISSUE TITLE
[bug] 쪽지방 리스트 쪽지 하나 있는 경우

### ISSUE THREAD

**Issue by LeeJE20** [Wingle-SMWU/Wingle-Backend#142]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 쪽지방 리스트 보기 시 쪽지방에 쪽지가 하나만 있는 경우 에러 발생

## 📋 TODO
- [ ] 쪽지 createdtime 비교 로직 수정
