### ISSUE TITLE
[fix] ApiLoggingFilter 오류 수정 

### ISSUE THREAD

**Issue by LeeJE20** [Wingle-SMWU/Wingle-Backend#156]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- form-data가 아닌 api에서 오류 발생
- 원인: request.getContentType().startsWith()에서 request.getContentType()에 null값이 들어감

## 🎯 Goal
- null값인 경우 분기 처리되어야 함

## 📋 TODO
- [ ] null 방지
