### ISSUE TITLE
[feature] 글쓰기 객체 만들기

### ISSUE THREAD

**Issue by LeeJE20** [Wingle-SMWU/Wingle-Backend#16]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- article, comment, message는 글쓰기 객체를 상속 받아서 만들 예정
- 공통 기능을 객체로 만듦

## 📋 TODO
- [ ] Writing 객체 만들기
