### ISSUE TITLE
[fix] 커뮤니티 정렬 수정

### ISSUE THREAD

**Issue by Lightieey** [Wingle-SMWU/Wingle-Backend#160]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [ ] 이슈 제목 작성 [FEATURE] 개발할 기능
- [ ] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 커뮤니티 정렬 수정

## 📋 TODO
- [ ] 게시글 전체 리스트 조회 정렬 (최신순)
- [ ] 댓글 전체 리스트 조회 정렬 (최신 댓글이 제일 밑에)
