### ISSUE TITLE
[feature] 회원가입 거절사유 메모 유저아이디 암호화

### ISSUE THREAD

**Issue by LeeJE20** [Wingle-SMWU/Wingle-Backend#162]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 회원가입 거절사유 메모 유저아이디 암호화

## 📋 TODO
- [ ] 할 일
