### ISSUE TITLE
[bug] DB 커넥션 에러

### ISSUE THREAD

**Issue by LeeJE20** [Wingle-SMWU/Wingle-Backend#165]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 빌드 시 테스트코드 할 때 DB 커넥션 에러 발생

## 📋 TODO
- [ ] 세션 하나로 유지
