### ISSUE TITLE
[fix] 커뮤니티 최대 글자수 수정

### ISSUE THREAD

**Issue by Lightieey** [Wingle-SMWU/Wingle-Backend#166]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [ ] 이슈 제목 작성 [FEATURE] 개발할 기능
- [ ] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 커뮤니티 최대 글자수 수정

## 📋 TODO
- [ ] 게시글 최대 1000자 - 2000byte
- [ ] 댓글 최대 500자 - 1000byte
- [ ] Entity에서 TEXT로 설정
- [ ] RequestDto에서 size 설정
