### ISSUE TITLE
[feature] 프로필 상세조회 프로퍼티 추가

### ISSUE THREAD

**Issue by damda0904** [Wingle-SMWU/Wingle-Backend#173]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [ ] 이슈 제목 작성 [FEATURE] 개발할 기능
- [ ] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 설명을 작성해주세요

## 📋 TODO
- 3가지 프로퍼티 추가
    - 사용언어
    - 자기소개
    - 관심사
