### ISSUE TITLE
[feature] web cors 해결

### ISSUE THREAD

**Issue by damda0904** [Wingle-SMWU/Wingle-Backend#178]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [ ] 이슈 제목 작성 [FEATURE] 개발할 기능
- [ ] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 설명을 작성해주세요

## 📋 TODO
- [ ] 웹서버 cors 문제 해결
