### ISSUE TITLE
[feature] JaCoCo 테스트 제외

### ISSUE THREAD

**Issue by LeeJE20** [Wingle-SMWU/Wingle-Backend#18]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 비즈니스 로직이 없는 코드 제외
- common 패키지 제외

## 📋 TODO
- [ ] gradle 수정
- [ ] Lombok 제외
