### ISSUE TITLE
[feature] 이메일 문구 수정

### ISSUE THREAD

**Issue by LeeJE20** [Wingle-SMWU/Wingle-Backend#185]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 가입 완료 문구
- 가입 승인 문구
- 가입 거절 문구

## 📋 TODO
- [ ] 이메일 문구 수정
