### ISSUE TITLE
[fix] 커뮤니티 글자수 수정

### ISSUE THREAD

**Issue by Lightieey** [Wingle-SMWU/Wingle-Backend#194]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 커뮤니티 글자수 수정 (1차 QA)
- @size validation 수정 
  개행문자(whitespace)가 escape문자로 들어와서 글자수가 달라짐 (더 늘어나는 문제)
  ex) 키보드 입력으로 엔터 -> 1자리, '/n' -> 2자리로 카운트됨
  - 1안. @size 어노테이션 max값을 늘린다.
  - 2안. @size 어노테이션 대신 whitespace를 제거하고 length check하는 함수를 직접 만들어서 service 단에서 체크한다.
  

## 📋 TODO
- [x] 게시글 글자수 수정
- [x] 댓글 글자수 수정
- [x] @size validation 수정
