### ISSUE TITLE
[feature] Jacoco 환경 설정

### ISSUE THREAD

**Issue by yujin113** [Wingle-SMWU/Wingle-Backend#2]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- build.gradle에 Jacoco 설정 추가

## 📋 TODO
- [x] jacoco 세팅
