### ISSUE TITLE
[feature] 게시판 조회

### ISSUE THREAD

**Issue by LeeJE20** [Wingle-SMWU/Wingle-Backend#20]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 게시글 관련 기능 구현

## 📋 TODO
- [x] 게시판 엔티티 생성
- [x] 게시판 목록 보기
