### ISSUE TITLE
[add] 닉네임 양식 검증

### ISSUE THREAD

**Issue by Lightieey** [Wingle-SMWU/Wingle-Backend#203]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [ ] 이슈 제목 작성 [FEATURE] 개발할 기능
- [ ] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
1차 기획 QA
- 닉네임 양식 검증 - 한글/영문/숫자 2자 이상 10자 미만

## 📋 TODO
- [ ] custom validation check 만들기
