### ISSUE TITLE
[bug] 중복 이메일 res 수정

### ISSUE THREAD

**Issue by Lightieey** [Wingle-SMWU/Wingle-Backend#208]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [ ] 이슈 제목 작성
- [ ] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 버그를 재현하려면 어떻게 해야 하는지
- 내가 한 행동 (구체적)
- 이용 환경 (os, 브라우저 등등)

중복 이메일 res 오류 메시지가 "회원가입이 불가능한 이메일입니다."로 뜸
기존에 checkDuplicatedEmail()이 isSignupAvailableEmail()로 바뀌면서 생긴 문제

## 🎯 Goal
- 정상 동작이면 어떻게 되어야 하는지
"이미 가입된 유저입니다"가 떠야 함

## 📋 TODO
- [ ] isSignupAvailableEmail 수정
