### ISSUE TITLE
[feature] 회원가입 학교 학과 학번 추가

### ISSUE THREAD

**Issue by LeeJE20** [Wingle-SMWU/Wingle-Backend#218]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [ ] 이슈 제목 작성 [FEATURE] 개발할 기능
- [ ] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 학교 리스트 API
- 학교에 해당하는 학과 리스트 API
- 학번 입력

## 📋 TODO
- [ ] 학교 리스트 API
  - [ ] 학교 리스트 엔티티
  - [ ] 학교 리스트 DTO
- [ ] 회원가입 DTO 변경
- [ ] 회원가입 시 학교 학과 학번 입력
