### ISSUE TITLE
[fix] 익명 게시판 사용자 구분

### ISSUE THREAD

**Issue by Lightieey** [Wingle-SMWU/Wingle-Backend#224]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [ ] 이슈 제목 작성 [FEATURE] 개발할 기능
- [ ] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 익명 게시판 사용자 구분

## 📋 TODO
- [ ] 익명 게시판에서 게시글, 댓글 조회할 때 userId 0 대신 암호화댄 userId로 수정
