### ISSUE TITLE
[feature] profile entity 생성

### ISSUE THREAD

**Issue by gdakate** [Wingle-SMWU/Wingle-Backend#23]
## ✅ Checklist
- [ ] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [ ] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 설명을 작성해주세요

## 📋 TODO
- [ ] 할 일
