### ISSUE TITLE
[feature] 이메일 반응형

### ISSUE THREAD

**Issue by LeeJE20** [Wingle-SMWU/Wingle-Backend#237]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [ ] 이슈 제목 작성 [FEATURE] 개발할 기능
- [ ] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 이메일 내용 반응형 추가

## 📋 TODO
- [ ] 이메일 내용 반응형 추가
