### ISSUE TITLE
[feature] S3 설정

### ISSUE THREAD

**Issue by yujin113** [Wingle-SMWU/Wingle-Backend#24]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- S3Config, S3Util 작성

## 📋 TODO
- [ ] S3Config
- [ ] S3Util
