### ISSUE TITLE
[feature] 회원가입 학교 코드

### ISSUE THREAD

**Issue by LeeJE20** [Wingle-SMWU/Wingle-Backend#243]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 학교 Id 대신 학교 코드로 회원가입
## 📋 TODO
- [ ] 할 일
