### ISSUE TITLE
[feature] 영문 이메일

### ISSUE THREAD

**Issue by LeeJE20** [Wingle-SMWU/Wingle-Backend#249]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 외국인 이용자에게 영문 이메일 보내기

## 📋 TODO
- [ ] 외국인 이용자에게 영문 이메일 보내기
