### ISSUE TITLE
[bug] 복호화 오류

### ISSUE THREAD

**Issue by Lightieey** [Wingle-SMWU/Wingle-Backend#268]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [ ] 이슈 제목 작성
- [ ] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 버그를 재현하려면 어떻게 해야 하는지
  특정 memberId를 복호화하려고 할 때 실패함.
- 내가 한 행동 (구체적)
  admin waiting list 에서 특정 memberId를 눌러 자세히 조회하려고 할 때 복호화 오류가 남.
- 이용 환경 (os, 브라우저 등등)

## 🎯 Goal
- 정상 동작이면 어떻게 되어야 하는지
  정상적으로 복호화가 되어야 함

## 📋 TODO
- [ ] 할 일
