### ISSUE TITLE
[feature] 이메일 중복 검사하기

### ISSUE THREAD

**Issue by KimRiun** [Wingle-SMWU/Wingle-Backend#27]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- DB에 이미 존재하는 이메일 및 닉네임이 있는지 검사하는 인터페이스입니다.
- MemberService에서 해당 인터페이스를 구현하여 이미 존재하는 이메일인지 검사합니다.
- 중복된 이메일이 존재하는지, 아닌지 2가지 경우를 테스트합니다.

## 📋 TODO
- [x] 인터페이스 생성
- [x] 중복 검사 함수 선언부 만들기
- [x] 중복 검사 구현
- [x] 중복 검사 테스트 코드 작성
