### ISSUE TITLE
[bug] deploy.yml 빌드 오류

### ISSUE THREAD

**Issue by yujin113** [Wingle-SMWU/Wingle-Backend#34]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 테스트 Fail로 인해 빌드가 안되는 문제 발생
- 테스트가 잘 돌아갈 수 있는 환경 설정 필요

## 🎯 Goal
- 빌드 성공

## 📋 TODO
- [ ] 테스트 통과시키기
