### ISSUE TITLE
[bug] hello world health check

### ISSUE THREAD

**Issue by yujin113** [Wingle-SMWU/Wingle-Backend#40]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- Security Config에 antMatchers 추가해주기

## 🎯 Goal
- 서버 url 접속 시 hello world가 나온다.

## 📋 TODO
- [ ] SecurityConfig 수정
