### ISSUE TITLE
[feature] 회원가입 API 수정

### ISSUE THREAD

**Issue by yujin113** [Wingle-SMWU/Wingle-Backend#46]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 프로필 객체 저장
- 이메일 중복 확인
- requestDto에 isAvailable 추가, 약관 변수명 수정

## 📋 TODO
- [x] 프로필 객체 저장
- [x] 이메일 중복 확인
- [x] requestDto에 isAvailable 추가, 약관 변수명 수정
- [x] validateEmail 없애고 Email 어노테이션 붙이기
