### ISSUE TITLE
[feature] RedisConfig 수정

### ISSUE THREAD

**Issue by yujin113** [Wingle-SMWU/Wingle-Backend#48]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- RedisConfig 비밀번호 인증

## 📋 TODO
- [x] RedisConfig에 비밀번호 추가
