### ISSUE TITLE
[feature] 학생증 사진 업로드하기

### ISSUE THREAD

**Issue by KimRiun** [Wingle-SMWU/Wingle-Backend#51]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 회원가입시 학생증 사진을 S3에 업로드하고, DB에 url을 저장하는 API입니다.

## 📋 TODO
- [ ] 이미지 디코딩
- [ ] S3연결
- [ ] S3에 이미지 업로드
- [ ] 업로드한 이미지 url가져오기
- [ ] url을 DB에 저장하기
- [ ] S3연결끊기, 자원반납
- [ ] 결과 전송

**Comment by KimRiun** [comment]
회원가입 누르면 바로 S3에 업로드되므로 따로 API를 만들지 않기로 결정되었습니다.
