### ISSUE TITLE
[feature] 수락 대기 목록 조회 API

### ISSUE THREAD

**Issue by yujin113** [Wingle-SMWU/Wingle-Backend#53]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 수락 대기 목록 조회 API 구현

## 📋 TODO
- [ ] 관리자 계정 넣기
- [ ] 수락 대기 목록 조회 API
