### ISSUE TITLE
[refactor] member 폴더 구조 정리

### ISSUE THREAD

**Issue by yujin113** [Wingle-SMWU/Wingle-Backend#54]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- entity, service 따로 뺄 것

## 📋 TODO
- [x] 폴더 구조 정리
