### ISSUE TITLE
[feature] 로그인 API 수정

### ISSUE THREAD

**Issue by yujin113** [Wingle-SMWU/Wingle-Backend#58]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 응답에 관리자 여부 넣기

## 📋 TODO
- [ ] response 변경
