### ISSUE TITLE
[feature] BaseResponse 생성

### ISSUE THREAD

**Issue by yujin113** [Wingle-SMWU/Wingle-Backend#6]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- BaseResponse 작성
- 성공, 에러 코드 Enum 작성

## 📋 TODO
- [x] BaseResponse
- [x] 성공 Enum
- [x] 에러 Enum
