### ISSUE TITLE
[bug] is로 시작하는 변수명이 json으로 변환될 때 is가 없어지는 네이밍 불일치 문제 해결

### ISSUE THREAD

**Issue by KimRiun** [Wingle-SMWU/Wingle-Backend#70]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- ResponseDto에서 변수명 isAvailable이 json으로 전달될 때 available 이라는 이름으로 변경된다는 것을 인지하였습니다. 
![image](https://user-images.githubusercontent.com/56223389/220030313-9a8498a4-74a5-4290-9774-8f739eb746ea.png)

- 원인 : Jackson은 직렬화 및 역직렬화에 getter 및 setter 메서드를 사용합니다. 이때 get, set, is와 같은 접두사 뒤에 오는 항목을 json 필드의 key로 사용합니다. 그런데 기본형 boolean타입 변수인 isAvailable의 경우 롬복으로 만들어지는 함수명이 isIsAvailable이 아니라 isAvailable입니다. 그래서 is가 생략된 available이 전달되는 것입니다. 또 다른 예시로 Boolean타입이었을 경우 생성되는 메소드명은 getIsAvailable입니다. 이때는 get이 생략된 isAvailable이 json에서 key가 됩니다.
![image](https://user-images.githubusercontent.com/56223389/220023690-c851b0af-3229-48cc-a328-d1b7e6e3e381.png)

- 프론트와 API 소통시 주고받는 변수명이 다르면 문제가 되므로 API문서와 이름을 일치시켜야 합니다.
- 따라서 2가지 방안이 있습니다.
    1. boolean대신 Boolean 타입을 사용하여 isAvailable이라는 이름 유지하기
    2. boolean타입을 유지하되 available이라는 이름 사용하기
- 2번으로 결정하였습니다. 이유는 Boolean일 경우 null이 될 수도 있는데 available은 null을 담을 필요가 없기 때문입니다. 코드에 isAvailable도 그대로 남겨두되, API문서만 수정하는 방향으로 가도록 하겠습니다.

## 📋 TODO
- [ ] API문서에 isAvailable을 available로 바꾸기
