### ISSUE TITLE
[feature] 수락 거절, 완료 목록 조회

### ISSUE THREAD

**Issue by yujin113** [Wingle-SMWU/Wingle-Backend#73]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 수락 거절, 완료 목록 조회 API 구현

## 📋 TODO
- [x] 수락 거절 목록 조회 API
- [x] 수락 완료 목록 조회 API
