### ISSUE TITLE
[refactor] 로깅 수정

### ISSUE THREAD

**Issue by yujin113** [Wingle-SMWU/Wingle-Backend#75]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- health check로 / 가 호출되는 부분은 로그에 남지 않도록 수정

## 📋 TODO
- [ ] 로깅 수정
