### ISSUE TITLE
[feature] 로깅 세팅

### ISSUE THREAD

**Issue by yujin113** [Wingle-SMWU/Wingle-Backend#8]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 로깅 설정 파일 만들기
- 로깅 AOP 적용

## 📋 TODO
- [x] logback-spring.xml 작성
- [x] AOP 적용
