### ISSUE TITLE
[feature] 프로필 등록 여부 설정

### ISSUE THREAD

**Issue by yujin113** [Wingle-SMWU/Wingle-Backend#87]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 프로필 등록 여부 변경 로직 구현

## 📋 TODO
- [ ] 프로필 등록 여부 변경 로직 구현
