### ISSUE TITLE
[feature] BaseEntity 생성

### ISSUE THREAD

**Issue by LeeJE20** [Wingle-SMWU/Wingle-Backend#9]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- updatedAt, createdAt, isDeleted 클래스 변수를 갖는다
- 자동으로 updatedAt, createdAt를 update한다
- soft delete 적용을 위해 delete 연산 시 isDeleted를 true로 만든다

## 📋 TODO
- [ ] 클래스 생성
- [ ] @CreatedDate, @LastModifiedDate 적용
