### ISSUE TITLE
[fix] 회원가입 로직 수정

### ISSUE THREAD

**Issue by yujin113** [Wingle-SMWU/Wingle-Backend#91]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- 응답 DTO nickname 로직 수정

## 📋 TODO
- [ ] 프로필 객체의 nickname으로 조회
