### ISSUE TITLE
[feature] CORS 문제 해결

### ISSUE THREAD

**Issue by LeeJE20** [Wingle-SMWU/Wingle-Backend#94]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성 [FEATURE] 개발할 기능
- [x] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- CORS 문제를 해결
- 프론트 도메인이 확정되지 않은 관계로 일단 모든 도메인 허용할 예정
- 나중에 프론트 도메인만 허용되게 변경해야함

## 📋 TODO
- [ ] CORS 문제 해결
