### ISSUE TITLE
[refactor] 댓글 테스트 코드 작성

### ISSUE THREAD

**Issue by Lightieey** [Wingle-SMWU/Wingle-Backend#99]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [ ] 이슈 제목 작성 [FEATURE] 개발할 기능
- [ ] Assigneers, Labels, Projects, Milestone 붙여주세요

## ✏️ Description
- Community-Comment 관련 기능 테스트 코드 작성

## 📋 TODO
- [ ] CommentRepository 테스트코드 작성
- [ ] CommentService 테스트코드 작성
- [ ] CommentController 테스트코드 작성
